version: '3'
services:
    # node
    result:
        build: ./result
        volumes:
            - ./result:/app
            - /app/node_modules
        ports:
            - "5001:80"
        depends_on:
            - postgres
        container_name: "dev_result"
    postgres:
        image: postgres
        #build: ./backend/postgres
        environment: 
            - POSTGRES_PASSWORD=baron
            - POSTGRES_USER=baron
            #- POSTGRES_DB=brn
            #- POSTGRES_ROOT_USER=monty
        volumes:
            - ./volumes/pgdata:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/dump.sql
        ports: 
            - "5432:5432"
        container_name: "dev_postgres"
    redis:
        image: redis
        ports:
            - "6379:6379"
        container_name: "dev_redis"
    #worker:
    #    build: ./worker
    #    ports:
    #        - "${PORT_WORKER_SERVICE}:${PORT_WORKER_SERVICE}"
    #    container_name: "dev_worker"
    # flask
    poll:
        build: ./poll
        ports:
            - "5000:80"
        #volumes:
        #    - ./poll:/app
        container_name: "dev_poll"
