version: '3'
services:
    #node:
    #    build: ./backend/node
    #    volumes:
    #        - ./backend/node:/app
    #        - .env:/app/
    #    ports:
    #        - "${PORT_NODE_SERVICE}:${PORT_NODE_SERVICE}"
    #    container_name: ${PROJECT_NAME}_node
    postgres:
        build: ./backend/postgres
        environment: 
            - POSTGRES_PASSWORD=baron
            - POSTGRES_USER=baron
            - POSTGRES_DB=brn
        volumes: 
            - ./backend/postgres/volumes/pgdata:/var/lib/postgresql/data
        ports: 
            - "${PORT_POSTGRES_SERVICE}:${PORT_POSTGRES_SERVICE}"
        container_name: ${PROJECT_NAME}_postgres
    #redis:
    #    build: ./backend/redis
    #    ports:
    #        - "${PORT_REDIS_SERVICE}:${PORT_REDIS_SERVICE}"
    #    container_name: "${PROJECT_NAME}_redis"
    #worker:
    #    build: ./backend/worker
    #    ports:
    #        - "${PORT_WORKER_SERVICE}:${PORT_WORKER_SERVICE}"
    #    container_name: ${PROJECT_NAME}_java
    flask:
        build: ./frontend/flask
        ports:
            - "${PORT_FLASK_SERVICE}:5000"
        volumes: 
            - ./frontend/flask/app:/app
        container_name: ${PROJECT_NAME}_flask