version: '3'
services:
    result:
        build: ./result
        volumes:
            - ./result:/app
            - /app/node_modules
        ports:
            - "${RESULT_PORT}:80"
        depends_on:
            - postgres
        container_name: "dev_result"
        restart: on-failure
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        volumes:
            - ./volumes/pgdata:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/dump.sql
        ports: 
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        container_name: "dev_postgres"
        restart: on-failure
    redis:
        image: redis
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        container_name: "dev_redis"
        restart: on-failure
        #worker:
    #    build: ./worker
    #    ports:
    #        - "${PORT_WORKER_SERVICE}:${PORT_WORKER_SERVICE}"
    #    container_name: "dev_worker"
    #    restart: on-failure
    poll:
        build: ./poll
        ports:
            - "${POLL_PORT}:80"
        volumes:
            - ./poll:/app
            - .env:/app/.env
        container_name: "dev_poll"
        restart: on-failure
